version: "3.9"
services:
  server:
    image: registry.gitlab.com/altercode/astroneer-linux:latest
    container_name: astroneer
    volumes:
      - ./saves:/astroneer/Astro/Saved/SaveGames
      # Uncomment this if you want also the server configs to be mounted
      #- ./configs:/astroneer/Astro/Saved/Config/WindowsServer
    restart: unless-stopped
    environment:
      OWNER_NAME: 'yoursteamname'
      OWNER_GUID: '0'
      SERVER_PASSWORD: 'my_secret'
      SAVE_NAME: 'SAVE_1'
    ports:
      - "30877:30877/udp"
      - "30877:30877/tcp"
